version: '3.9'

services:
  ryu:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom/ryu-controller:latest
    container_name: ryu_controller
    # command: command to run controller here after we have it setup
    volumes:
      - ./ryu_app:/ryu_app
    working_dir: /ryu_app
    ports:
      - "6633:6633"  # OpenFlow default port
      - "8080:8080"  # Ryu REST API (if needed)
    network_mode: host
    tty: true # keep container open

  mininet:
    image: iwaseyusuke/mininet
    container_name: mininet
    privileged: true
    volumes:
      - ./mn_scripts:/mn_scripts
    # Set the working directory as the mininet scripts
    working_dir: /mn_scripts
    network_mode: host
    depends_on:
      - ryu
    tty: true # keep container open
